name: itcompany
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_lorem: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/bird.jpeg
    - images/breeding.jpg
    - images/consulting.jpg
    - images/cover3.jpg
    - images/development.jpg
    - images/education.jpg
    - images/energy.jpg
    - images/health.jpg
    - images/maintenance.jpg
    - images/robotic.jpg
    - images/telecom.jpg
    - images/training.jpg
